version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.2.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  test-flight:
    macos:
      xcode: "11.2.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test_flight
      BUILD_NUMBER: $CIRCLE_BUILD_NUM
    steps:
      - checkout
      - run: bundle install
      - run: brew install gpg
      - run: 
          name: Import Keys
          command: echo $SECRETS_ENCRYPTION_KEY | base64 --decode | gpg --import
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-test-upload:
    jobs:
      - build-and-test
      - test-flight:
          filters:
            branches:
              only: /release_.*/
          requires:
            - build-and-test