# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do

  before_all do
    setup_circle_ci
    cocoapods
  end

  desc "Starting Unit Tests"
  lane :tests do
    run_tests(scheme: "SmartReceipts")
   end

  desc "Upload to TestFlight"
  lane :test_flight do
    sync_code_signing(type: "appstore")
  	increment_build_number(build_number: ENV["BUILD_NUMBER"])
  	build_app(
  		workspace: "SmartReceipts.xcworkspace", 
      scheme: "SmartReceipts",
      configuration: "Release",
      export_method: "app-store"
    )
  	upload_to_testflight(
  		skip_submission: true, 
  		skip_waiting_for_build_processing: true, 
  		apple_id: "905698613"
  		)
	end

end

